# Generated by Django 5.2 on 2025-05-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user_list", "Может просматривать список пользователей"),
                    (
                        "can_block_user",
                        "Может блокировать пользователей (is_active=False)",
                    ),
                    (
                        "can_view_all_users",
                        "Может просматривать всех пользователей (не только своих)",
                    ),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
