# Generated by Django 5.2 on 2025-04-08 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_message",
                    models.CharField(
                        help_text="Какова тема письма?",
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "message_body",
                    models.TextField(
                        help_text="Введите сообщение", verbose_name="Тело сообщения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="message_attachments/%Y/%m/%d/",
                        verbose_name="Вложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["-created_at", "subject_message"],
                "indexes": [
                    models.Index(
                        fields=["subject_message"],
                        name="mailing_ser_subject_e099f9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите свою электронную почту",
                        max_length=50,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите Ф.И.О.",
                        max_length=100,
                        verbose_name="ФИО получателя",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные данные",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
                "ordering": ["full_name", "email"],
                "indexes": [
                    models.Index(fields=["email"], name="mailing_ser_email_d71cac_idx"),
                    models.Index(
                        fields=["full_name"], name="mailing_ser_full_na_15d13a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_shipment",
                    models.DateTimeField(
                        help_text="Дата и время первой отправки",
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "end_shipment",
                    models.DateTimeField(
                        help_text="Дата и время окончания отправки",
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "Выберите статус рассылки"),
                            ("CREATED", "Создана"),
                            ("LAUNCHED", "Запущена"),
                            ("COMPLETED", "Завершена"),
                        ],
                        help_text="Выберите статус рассылки",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Указывает, активна ли рассылка",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mailing_service.message",
                        verbose_name="Cообщения",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="mailing_service.recipient", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["-first_shipment", "status"],
            },
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_attempt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_service.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailing_service.recipient",
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["-date_of_attempt"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="mailing_ser_status_37c5fc_idx"
                    ),
                    models.Index(
                        fields=["date_of_attempt"],
                        name="mailing_ser_date_of_6a18a6_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status"], name="mailing_ser_status_a56c25_idx"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(
                fields=["first_shipment"], name="mailing_ser_first_s_e04d81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(
                fields=["is_active"], name="mailing_ser_is_acti_f37364_idx"
            ),
        ),
    ]
