# Generated by Django 5.2 on 2025-05-08 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0003_remove_recipient_token_mailing_owner_message_owner_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-first_shipment", "status"],
                "permissions": [
                    ("can_view_own_mailing", "Can view own mailings"),
                    ("can_change_own_mailing", "Can change own mailings"),
                    ("can_delete_own_mailing", "Can delete own mailings"),
                    ("can_start_own_mailing", "Can start own mailings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at", "subject_message"],
                "permissions": [
                    ("can_view_own_message", "Can view own messages"),
                    ("can_change_own_message", "Can change own messages"),
                    ("can_delete_own_messages", "Can delete own messages"),
                ],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name", "email"],
                "permissions": [
                    ("can_view_own_recipient", "Can view own recipients"),
                    ("can_change_own_recipient", "Can change own recipients"),
                    ("can_delete_own_recipient", "Can delete own recipients"),
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца рассылки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца сообщения",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
