# Generated by Django 5.2 on 2025-05-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0004_alter_mailing_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-first_shipment", "status"],
                "permissions": [
                    ("can_view_all_mailing", "Can view all mailings"),
                    ("can_change_own_mailing", "Can change own mailings"),
                    ("can_delete_own_mailing", "Can delete own mailings"),
                    ("can_start_all_mailing", "Can start all mailings"),
                    ("can_disable_mailing", "Can disable mailings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailinglog",
            options={
                "ordering": ["-date_of_attempt"],
                "permissions": [
                    ("can_view_all_logs", "Can view all logs"),
                    ("can_delete_logs", "Can delete logs"),
                ],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at", "subject_message"],
                "permissions": [
                    ("can_view_own_message", "Can view own messages"),
                    ("can_change_own_message", "Can change own messages"),
                    ("can_delete_own_messages", "Can delete own messages"),
                    ("can_view_all_messages", "Can view all messages"),
                    ("can_send_message", "Can send messages manually"),
                ],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name", "email"],
                "permissions": [
                    ("can_view_own_recipient", "Can view own recipients"),
                    ("can_change_own_recipient", "Can change own recipients"),
                    ("can_delete_own_recipient", "Can delete own recipients"),
                    ("can_view_all_recipients", "Can view all recipients"),
                    ("can_disable_recipient", "Сan disable recipients"),
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
