# Generated by Django 5.2 on 2025-05-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0005_alter_mailing_options_alter_mailinglog_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-first_shipment", "status"],
                "permissions": [
                    ("can_view_all_mailing", "Can view all mailings"),
                    ("can_change_own_mailing", "Can change own mailings"),
                    ("can_delete_own_mailing", "Can delete own mailings"),
                    ("can_disable_mailing", "Может отключать любые рассылки"),
                    ("can_start_mailing", "Может запускать любые рассылки"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
