# Generated by Django 5.2 on 2025-05-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0006_alter_mailing_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mailinglog",
            name="mailing_ser_status_37c5fc_idx",
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddIndex(
            model_name="mailinglog",
            index=models.Index(
                fields=["status", "owner"], name="mailing_ser_status_b17ecc_idx"
            ),
        ),
    ]
